#!/bin/bash

#set -xv
#id
source "/swcode/swcode.bash" ;
rerunasroot "$@" ;

scriptdir="$(realpath --canonicalize-existing -- "$(dirname -- "$0")")"
scriptdir_withslash="${scriptdir}/"
scriptself="${scriptdir}/$(basename -- "$0")"
if test -z "$scriptdir" -o ! -x "$scriptself"; then
  echo "Can't find scriptdir ("$scriptdir") or script("$0") doesn't exist as executable file ("$scriptself")" >&2
  exit 1
fi
#set -xev
set -e
source "${scriptdir_withslash}vars.env"
set +e
#set +xev

function print_all_the_ff_hostnames() {
  allffhosts=(firefoxhelloooooowoooorl.clock firefox_blocked_domain.tld)
  res="("
  first=1
  for h in "${allffhosts[@]}"; do
    if test "$first" == "1"; then
      first="0"
      res+="${h}"
    else
      res+="|${h}"
    fi
  done
  res+=")"
  cat /usr/lib64/firefox/browser/defaults/preferences/vendor.js /patches/portage/www-client/firefox.reused/*.patch | grep -Ew "$res" | sed -re 's/^.*:\/\/([0-9A-Za-z_\.-]*'"$res"').*$/\1/' | sort -u
  #TODO: ensure only valid hostname chars (eg. no spaces/tabs) are in the resulting output list!
}

function main() {

local diff
if test "$1" != "nodiff"; then
  if which colordiff >/dev/null 2>&1; then
    diff=colordiff
    if test -n "$DEBUG" -a "0$DEBUG" != "00"; then
      echo "Using '$diff'" >&2
    fi
  else
    diff=diff
  fi
fi

destfile="${hostsdgen_dir_withslash}01200_firefox_blocks.ag.conf"
tmpfile="$(mktemp --tmpdir="/tmp" -t -- "etc_hostsdgen_01200_firefox_blocks_conf_XXXXXXXXXX_$(date --iso-8601=ns|tr ':,+' '_')")"
if test -n "$DEBUG" -a "0$DEBUG" != "00"; then
  echo "Using temp file '$tmpfile'" >&2
fi
#date --iso-8601=ns|tr ':,+' '_' is like 2021-06-10T00_15_51_904809374_02_00

#using *.conf mainly for vim syntax highlighting and to avoid catching any scripts(*.bash) residing in there.

set -e
cat > "$tmpfile" <<EOF
#Autogenerated by '$0' script (aka '$scriptself') (in order to create a new '$destfile') on `date`
#
#urls that are used in user.js aka vendor.js
#
EOF
set +e

local ip
ip="/bin/ip"
if ! test -x "$ip"; then
  ip="ip"
fi

#set +e
local ec
"${ip}" address >/dev/null 2>&1 ; ec="$?"
if test "$ec" -ne "0"; then
  echo "command '$ip address' doesn't work correctly!" >&2
  echo "exit code was '$ec" >&2
  exit 1
fi

local iface
iface="$(route -n |grep '^0.0.0.0' |head -1| sed -re 's/.*[[:space:]]//')"
if test -z "$iface"; then
  echo "$scriptself: Couldn't find LAN interface" >&2
  exit 1
fi

#LAN IP that is:
local ipaddr
ipaddr="$(ip address show dev em1|grep -wF 'inet'|head -1| sed -re 's/[[:space:]]+//'|cut -f2 -d' '|cut -f1 -d'/')"
if test -z "$ipaddr"; then
  echo "$scriptself: Couldn't find IP for LAN interface '$iface'" >&2
  exit 1
fi

set -e
print_all_the_ff_hostnames | sed -re 's|^(.*)$|0.0.0.0 \1|' >> "$tmpfile"

echo "# All done from '$0' aka '$scriptself'." >> "$tmpfile"
set +e
if test "$1" != "nodiff" -a -e "$destfile" ; then
  "$diff" -up -- "$destfile" "$tmpfile" | less
fi
set -e
chmod a+r -- "$tmpfile"
#Overwrite current, ACID-like:
mv -- "$tmpfile" "$destfile"
#^ used temp file so that resulting output file won't be garbled
#^ used lockedcall for the same reason + extra safety
set +e

echo "All good! '$destfile' (re)generated."
} #main

lockedcall 303 main "$@"

