#!/bin/bash

#set -xv
#id
source "/swcode/swcode.bash" ;
rerunasroot "$@" ;

scriptdir="$(realpath --canonicalize-existing -- "$(dirname -- "$0")")"
scriptdir_withslash="${scriptdir}/"
scriptself="${scriptdir}/$(basename -- "$0")"
if test -z "$scriptdir" -o ! -x "$scriptself"; then
  echo "Can't find scriptdir ("$scriptdir") or script("$0") doesn't exist as executable file ("$scriptself")" >&2
  exit 1
fi
#set -xev
set -e
source "${scriptdir_withslash}vars.env"
set +e
#set +xev


function main() {

if test "$1" != "nodiff"; then
  if which colordiff >/dev/null 2>&1; then
    diff=colordiff
    if test -n "$DEBUG" -a "0$DEBUG" != "00"; then
      echo "Using '$diff'" >&2
    fi
  else
    diff=diff
  fi
fi

destfile="${hostsdgen_dir_withslash}00030_thishost.conf"
tmpfile="$(mktemp --tmpdir="/tmp" -t -- "etc_hostsdgen_00030_thishost_conf_XXXXXXXXXX_$(date --iso-8601=ns|tr ':,+' '_')")"
if test -n "$DEBUG" -a "0$DEBUG" != "00"; then
  echo "Using temp file '$tmpfile'" >&2
fi
#date --iso-8601=ns|tr ':,+' '_' is like 2021-06-10T00_15_51_904809374_02_00

#using *.conf mainly for vim syntax highlighting and to avoid catching any scripts(*.bash) residing in there.

set -e
cat > "$tmpfile" <<EOF
#Autogenerated by '$0' script (aka '$scriptself') (in order to create a new '$destfile') on `date`
EOF
sethostname="$(cat "/etc/conf.d/hostname" | grep -v '^\s*#'|cut -f2 -d'"')"
if test -z "$sethostname"; then
  echo "Failed to get Gentoo's set hostname from /etc/conf.d/hostname" >&2
  exit 1
fi
actualhostname="$(hostname)"
if test -z "$sethostname"; then
  echo "Failed to get actual hostname via 'hostname' command" >&2
  exit 1
fi

if test "$sethostname" != "$actualhostname"; then
  echo "Set hostname ('$sethostname') differs than actual hostname ('$actualhostname')" >&2
  exit 1
fi

echo "127.0.1.1 ${actualhostname}.localdomain ${actualhostname}" >> "$tmpfile"
#^ some good reason why not 127.0.0.1 but I forgot! either way 127.0.0.0/8 will point to whatever's listening on local host, like ssh since it's listening on 0.0.0.0 !

echo "# All done from '$0' aka '$scriptself'." >> "$tmpfile"
set +e
if test "$1" != "nodiff" -a -e "$destfile" ; then
  "$diff" -up -- "$destfile" "$tmpfile" | less
fi
set -e
chmod a+r -- "$tmpfile"
#Overwrite current, ACID-like:
mv -- "$tmpfile" "$destfile"
#^ used temp file so that resulting output file won't be garbled
#^ used lockedcall for the same reason + extra safety
set +e

echo "All good! '$destfile' (re)generated."
} #main

lockedcall 302 main "$@"

